/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Administrateur.pdf;

import Entity.Session;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Amine
 */
public class PDF extends javax.swing.JFrame {

    /**
     * Creates new form PDF
     */
    public PDF() {
        initComponents();
        
        switch (Session.getInstance().getUser().getType()){
            case 's':
            case 'a':
                auteurTF.setText(((Entity.Administrateur)Session.getInstance().getUser().getCompte()).getPrenom() + " " + ((Entity.Administrateur)Session.getInstance().getUser().getCompte()).getNom());
                break;
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        auteurTF = new javax.swing.JTextField();
        titleTF = new javax.swing.JTextField();
        modePdfToggleButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PremierPageTA = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DernierePageTA = new javax.swing.JTextArea();
        viderPremierePageTA = new javax.swing.JButton();
        viderDernierePageTA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setText("Générer le PDF");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel1.setText("title:");

        jLabel2.setText("Auteur:");

        modePdfToggleButton.setText("Mode PDF: OFF");
        modePdfToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modePdfToggleButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Premiere page :");

        PremierPageTA.setColumns(20);
        PremierPageTA.setRows(5);
        jScrollPane1.setViewportView(PremierPageTA);

        jLabel4.setText("Derniere page :");

        DernierePageTA.setColumns(20);
        DernierePageTA.setRows(5);
        jScrollPane2.setViewportView(DernierePageTA);

        viderPremierePageTA.setText("Vider");
        viderPremierePageTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viderPremierePageTAMousePressed(evt);
            }
        });

        viderDernierePageTA.setText("Vider");
        viderDernierePageTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viderDernierePageTAMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modePdfToggleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(titleTF)
                                .addComponent(auteurTF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viderDernierePageTA))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viderPremierePageTA)))
                        .addGap(0, 422, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modePdfToggleButton)
                    .addComponent(jButton1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(auteurTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viderPremierePageTA))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viderDernierePageTA))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("C:\\"));
        chooser.setDialogTitle("choisir un répertoire");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            //création du chemin mta3 sauvegarde
            Session.getInstance().getPdfFile().setUrlDocument(chooser.getSelectedFile()+"\\"+titleTF.getText()+".pdf");
            
            //préparation du pdf document
            if (PremierPageTA.getText() != null)
                Session.getInstance().getPdfFile().setFirst(PremierPageTA.getText());

            if (DernierePageTA.getText() != null)
                Session.getInstance().getPdfFile().setLast(DernierePageTA.getText());

            if (Session.getInstance().getPdfFile().createPDFFile(titleTF.getText(), auteurTF.getText()))
                JOptionPane.showMessageDialog(null, "PDF généré avec succeés");
            else
                JOptionPane.showMessageDialog(null, "Erreur lors de la génération du PDF");
        } 
    }//GEN-LAST:event_jButton1MousePressed

    private void modePdfToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modePdfToggleButtonActionPerformed
        Session.getInstance().setModePdfOn(!Session.getInstance().isModePdfOn());
        modePdfToggleButton.setText((Session.getInstance().isModePdfOn()) ? "Mode PDF: ON" : "Mode PDF: OFF");
    }//GEN-LAST:event_modePdfToggleButtonActionPerformed

    private void viderPremierePageTAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viderPremierePageTAMousePressed
        PremierPageTA.setText(null);
    }//GEN-LAST:event_viderPremierePageTAMousePressed

    private void viderDernierePageTAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viderDernierePageTAMousePressed
        DernierePageTA.setText(null);
    }//GEN-LAST:event_viderDernierePageTAMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Session.getInstance().setModePdfOn(false);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDF().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DernierePageTA;
    private javax.swing.JTextArea PremierPageTA;
    private javax.swing.JTextField auteurTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton modePdfToggleButton;
    private javax.swing.JTextField titleTF;
    private javax.swing.JButton viderDernierePageTA;
    private javax.swing.JButton viderPremierePageTA;
    // End of variables declaration//GEN-END:variables
}
