/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Banissement;
import GUI.*;
import DAO.*;
import Entity.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.Exceptions.ProblemeTechniqueException;
/**
 *
 * @author Axel
 */
public class Banissement extends javax.swing.JFrame {
    private Conducteurs conducteur ; 
    private Passagers passager ;
    private String userBan ; 
    private Entity.Authentification authentification = new Entity.Authentification();
    /**
     * Creates new form Banissement
     */
    public Banissement() {
        initComponents();
       
    }
    public Banissement(Conducteurs conducteur,Passagers passager ,String userBan) {
        initComponents();
        this.conducteur=conducteur;
        this.passager= passager;
        this.userBan= userBan; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomPrenom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cause = new javax.swing.JTextArea();
        DateF = new javax.swing.JTextField();
        dateD = new javax.swing.JTextField();
        BannirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("Date début : ");

        jLabel3.setText("Date fin : ");

        jLabel4.setText("Cause : ");

        cause.setColumns(20);
        cause.setRows(5);
        jScrollPane1.setViewportView(cause);

        BannirBtn.setText("Bannir");
        BannirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BannirBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(dateD))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(35, 35, 35)
                            .addComponent(DateF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BannirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(NomPrenom)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DateF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(BannirBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       info();
    }//GEN-LAST:event_formWindowOpened

    private void BannirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BannirBtnMouseClicked
        if(cause.getText().equals("") || dateD.getText().equals("") || DateF.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Il y a des champs vides");
        }
        else
        {
            java.text.SimpleDateFormat df = new java.text.SimpleDateFormat("yyyy-mm-dd");
            Entity.Banissement ban = new Entity.Banissement();
            ban.setCause(cause.getText());
            try {
                    ban.setDateDebut(df.parse(dateD.getText()));
                    ban.setDateFin(df.parse(DateF.getText()));
            } catch (ParseException ex) {
                System.out.println("problem de date");
            }
            ban.setUser(authentification);
            Entity.Administrateur Admin = (Entity.Administrateur) Entity.Session.getInstance().getUser().getCompte() ; 
            ban.setIdAdministrateurs(Admin);
            BanissementsDAO banDAO = new   BanissementsDAO() ;
            try {
                if(banDAO.create(ban))
                {
                    JOptionPane.showMessageDialog(null, "Le conducteur "+conducteur.getNom()+" "+conducteur.getPrenom());
                    new Banissement().setVisible(false);
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "problem de ban");
                }
            } catch (ProblemeTechniqueException ex) {
                System.out.println("Problem de création");
            }
           
           
        }
    }//GEN-LAST:event_BannirBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public void info()
    {
        
        try {
            if (userBan.equals("c"))
            {
                authentification = AuthentificationDAO.getInstance().getByIdCompte(conducteur.getIdConducteurs());
                NomPrenom.setText("Le conducteur "+conducteur.getNom()+" "+conducteur.getPrenom());
            }
             else
            {
                 authentification = AuthentificationDAO.getInstance().getByIdCompte(passager.getIdPassagers());
                 NomPrenom.setText("Le passager"+passager.getNom()+" "+passager.getPrenom());
            }
        } catch (ProblemeTechniqueException ex) {
            System.out.println("Problème de récuperation d'une authentification");
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banissement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banissement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banissement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banissement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banissement().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BannirBtn;
    private javax.swing.JTextField DateF;
    private javax.swing.JLabel NomPrenom;
    private javax.swing.JTextArea cause;
    private javax.swing.JTextField dateD;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
