/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.UserDAO;
import Entity.Session;
import GUI.Administrateur.Accueil;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import metier.AuthentificationMetier;

/**
 *
 * @author Amine
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification2
     */
    
    private AuthentificationMetier authentificationMetier;
    
    public Authentification() {
        initComponents();
        
        authentificationMetier = new AuthentificationMetier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwdTF = new javax.swing.JPasswordField();
        connectBtn = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 310, 53, 14);
        getContentPane().add(loginTF);
        loginTF.setBounds(420, 300, 160, 30);

        jLabel2.setText("Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 360, 80, 14);
        getContentPane().add(pwdTF);
        pwdTF.setBounds(420, 350, 160, 30);

        connectBtn.setText("Connect");
        connectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                connectBtnMousePressed(evt);
            }
        });
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });
        getContentPane().add(connectBtn);
        connectBtn.setBounds(493, 400, 90, 23);

        errorMessageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        errorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(errorMessageLabel);
        errorMessageLabel.setBounds(320, 440, 260, 40);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background logo.png"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectBtnMousePressed

    }//GEN-LAST:event_connectBtnMousePressed

    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
        try {
            // TODO add your handling code here:
            if (authentificationMetier.verifierAccee(loginTF.getText(), pwdTF.getText()))
            {
                try {
                    Session.getInstance().setUser(UserDAO.getInstance().getUserByLogin(loginTF.getText()));
                } catch (ClassNotFoundException ex) {
                    System.out.println("p");
                } catch (SQLException ex) {
                    System.out.println("p");
                }
                Accueil acc=new Accueil();
                //this.setVisible(false);
                this.dispose();
                acc.setVisible(true);
            }
            else
            errorMessageLabel.setText("Veuillez vérifier votre login et/ou mot de passe");

        } catch (NoSuchAlgorithmException ex) {
            System.out.println("p");
        }
    }//GEN-LAST:event_connectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton connectBtn;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loginTF;
    private javax.swing.JPasswordField pwdTF;
    // End of variables declaration//GEN-END:variables
}
