/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.AuthentificationDAO;
import Entity.Session;
import javax.swing.JOptionPane;
import metier.AuthentificationMetier;
import utils.Exceptions.ProblemeTechniqueException;

/**
 *
 * @author Amine
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification2
     */
    
    private AuthentificationMetier authentificationMetier;
    
    public Authentification() {
        initComponents();
        
        authentificationMetier = new AuthentificationMetier();
    }
    
    private void verifierAuthentification()
    {
        if (loginTF.getText().equals("") && pwdTF.getText().equals(""))
            errorMessageLabel.setText("Les champs login et password sont vides.");
        else if (loginTF.getText().equals(""))
            errorMessageLabel.setText("Le champs login est vide.");
        else if (pwdTF.getText().equals(""))
            errorMessageLabel.setText("Le champs password est vide.");
        else
        {
         try {
            // TODO add your handling code here:
            if (authentificationMetier.verifierAccee(loginTF.getText(), pwdTF.getText()))
            {
                
                Session.getInstance().connexion(AuthentificationDAO.getInstance().getByLogin(loginTF.getText()));
                
                if (authentificationMetier.verifierBan(Session.getInstance().getUser().getIdAuthentification()))
                {
                    errorMessageLabel.setText(Session.getInstance().getMessage());
                }
                else
                {
                    if (Session.getInstance().getUser().getType() == 's')
                    {
                        GUI.SuperAdministrateur.Accueil acc = new GUI.SuperAdministrateur.Accueil();
                        acc.setVisible(true);
                    }
                    else if (Session.getInstance().getUser().getType() == 'a')
                    {
                        GUI.Administrateur.Accueil acc = new GUI.Administrateur.Accueil();
                        acc.setVisible(true);
                    }
                    else if (Session.getInstance().getUser().getType() == 'c')
                    {
                        GUI.Conductuer.Accueil acc = new GUI.Conductuer.Accueil();
                        acc.setVisible(true);
                    }
                    else if (Session.getInstance().getUser().getType() == 'p')
                    {
                        GUI.Passager.Accueil acc = new GUI.Passager.Accueil();
                        acc.setVisible(true);
                    }
                    this.dispose();
                }
            }
            else
            {
                pwdTF.setText("");
                pwdTF.requestFocus();
                errorMessageLabel.setText("Veuillez vérifier votre login et/ou mot de passe");
            }
        } catch (ProblemeTechniqueException ex) {
            errorMessageLabel.setText(ex.getMessage());
        }   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwdTF = new javax.swing.JPasswordField();
        connectBtn = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        InscriptionBtn = new javax.swing.JButton();
        contactBtn = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Covoiturage || Back Office");
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 310, 53, 14);
        getContentPane().add(loginTF);
        loginTF.setBounds(420, 300, 160, 30);

        jLabel2.setText("Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 360, 80, 14);

        pwdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdTFKeyPressed(evt);
            }
        });
        getContentPane().add(pwdTF);
        pwdTF.setBounds(420, 350, 160, 30);

        connectBtn.setText("Connect");
        connectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                connectBtnMousePressed(evt);
            }
        });
        getContentPane().add(connectBtn);
        connectBtn.setBounds(483, 400, 100, 23);

        errorMessageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        errorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(errorMessageLabel);
        errorMessageLabel.setBounds(320, 440, 260, 40);

        InscriptionBtn.setText("S'inscrire");
        InscriptionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InscriptionBtnMousePressed(evt);
            }
        });
        getContentPane().add(InscriptionBtn);
        InscriptionBtn.setBounds(480, 490, 90, 23);

        contactBtn.setText("Nous contacter");
        getContentPane().add(contactBtn);
        contactBtn.setBounds(320, 490, 110, 23);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background logo.png"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectBtnMousePressed
        verifierAuthentification();
    }//GEN-LAST:event_connectBtnMousePressed

    private void pwdTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdTFKeyPressed
        if (evt.getKeyCode()== 10)
            verifierAuthentification();
    }//GEN-LAST:event_pwdTFKeyPressed

    private void InscriptionBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InscriptionBtnMousePressed
        (new GUI.Inscription.Inscription()).setVisible(true);
    }//GEN-LAST:event_InscriptionBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InscriptionBtn;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton connectBtn;
    private javax.swing.JButton contactBtn;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loginTF;
    private javax.swing.JPasswordField pwdTF;
    // End of variables declaration//GEN-END:variables
}
