/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.GestionProfileConducteur;

import GUI.GestionProfil.*;
import Entity.*;
import DAO.*;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.Exceptions.ProblemeTechniqueException;

/**
 *
 * @author Ahmed
 */
public class GestionProfil extends javax.swing.JFrame {

    private Authentification authentification = new Authentification();
    Voiture voiture = new Voiture();
    Conducteurs conducteur = new Conducteurs() ; 

    /**
     * Creates new form GestionProfil
     */
    public GestionProfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomTf = new javax.swing.JTextField();
        prenomTf = new javax.swing.JTextField();
        adresseTf = new javax.swing.JTextField();
        numtelTf = new javax.swing.JTextField();
        datedenaissanceTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JTextField();
        confirmPasswordTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EnregistrerBtn = new javax.swing.JButton();
        AcceuilBtn = new javax.swing.JButton();
        ModifierBtn = new javax.swing.JButton();
        AnnulerBtn = new javax.swing.JButton();
        sexeTf = new javax.swing.JComboBox();
        formaDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        VoiturePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BagageBox = new javax.swing.JCheckBox();
        EnfantBox = new javax.swing.JCheckBox();
        TabacBox = new javax.swing.JCheckBox();
        ClimatiseurBox = new javax.swing.JCheckBox();
        ModeleTf = new javax.swing.JTextField();
        MarqueTf = new javax.swing.JTextField();
        AnneeTf = new javax.swing.JTextField();
        NbrPlaceTf = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        jLabel3.setText("Adresse");

        jLabel4.setText("Numero de telephone");

        jLabel5.setText("Date de naissance");

        jLabel6.setText("Sexe");

        jLabel7.setText("E-mail");

        nomTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTfActionPerformed(evt);
            }
        });

        jLabel8.setText("Password");

        jLabel9.setText("Confirmer password");

        EnregistrerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Enregistrer.png"))); // NOI18N
        EnregistrerBtn.setText("Enregistrer");
        EnregistrerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnregistrerBtnMouseClicked(evt);
            }
        });

        AcceuilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/quitter.png"))); // NOI18N
        AcceuilBtn.setText("Quiiter");
        AcceuilBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceuilBtnMouseClicked(evt);
            }
        });

        ModifierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/modifier.png"))); // NOI18N
        ModifierBtn.setText("Modifier");
        ModifierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierBtnMouseClicked(evt);
            }
        });
        ModifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBtnActionPerformed(evt);
            }
        });

        AnnulerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Annuler.png"))); // NOI18N
        AnnulerBtn.setText("Annuler");
        AnnulerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerBtnMouseClicked(evt);
            }
        });

        sexeTf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));

        formaDate.setText("yyyy-mm-dd");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Mon profil ");

        jLabel11.setText("Modele");

        jLabel12.setText("Marque");

        jLabel13.setText("Annee");

        jLabel14.setText("Nombre de place ");

        BagageBox.setText("Bagages");

        EnfantBox.setText("Enfants");

        TabacBox.setText("Tabac");

        ClimatiseurBox.setText("Climatisation");

        javax.swing.GroupLayout VoiturePanelLayout = new javax.swing.GroupLayout(VoiturePanel);
        VoiturePanel.setLayout(VoiturePanelLayout);
        VoiturePanelLayout.setHorizontalGroup(
            VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoiturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(VoiturePanelLayout.createSequentialGroup()
                            .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(47, 47, 47))
                        .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BagageBox)
                            .addComponent(TabacBox)))
                    .addComponent(jLabel14))
                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VoiturePanelLayout.createSequentialGroup()
                        .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VoiturePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClimatiseurBox)
                                    .addComponent(EnfantBox)))
                            .addGroup(VoiturePanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModeleTf)
                                    .addComponent(MarqueTf)
                                    .addComponent(AnneeTf))))
                        .addGap(52, 52, 52))
                    .addGroup(VoiturePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NbrPlaceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        VoiturePanelLayout.setVerticalGroup(
            VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoiturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VoiturePanelLayout.createSequentialGroup()
                        .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ModeleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(MarqueTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(AnneeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NbrPlaceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VoiturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BagageBox)
                    .addComponent(EnfantBox))
                .addGap(18, 18, 18)
                .addGroup(VoiturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TabacBox)
                    .addComponent(ClimatiseurBox))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Voiture.png"))); // NOI18N
        jButton1.setText("Ma voiture");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addComponent(AcceuilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EnregistrerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(ModifierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(AnnulerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailTf)
                                    .addComponent(datedenaissanceTf)
                                    .addComponent(numtelTf)
                                    .addComponent(passwordTf)
                                    .addComponent(confirmPasswordTf)
                                    .addComponent(sexeTf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomTf)
                                    .addComponent(prenomTf)
                                    .addComponent(adresseTf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(formaDate)
                                .addGap(16, 16, 16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VoiturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nomTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(prenomTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(adresseTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(numtelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(datedenaissanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(formaDate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(sexeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VoiturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcceuilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnregistrerBtn)
                    .addComponent(ModifierBtn)
                    .addComponent(AnnulerBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean verifierChamps() {
        String erreurMsg = "";
        boolean result = true;

        if (nomTf.getText().length() < 3) {
            erreurMsg += "Le nom doit au moins avoir trois caracteres.\n";
            result = false;
        }

        if (prenomTf.getText().length() < 3) {
            erreurMsg += "Le prenom doit au moins avoir trois caracteres.\n";
            result = false;
        }

        if (!utils.Validators.NumeroTelValidator(numtelTf.getText())) {
            erreurMsg += "Le numéro de téléphone n'est pas valide.\n";
            result = false;
        } else if (!utils.Validators.TailleNumTelValidator(numtelTf.getText())) {
            erreurMsg += "Le numéro de téléphone est supérieur a 8 chiffre .\n";
            result = false;
        } else if (!utils.Validators.NomPrenomValidator(nomTf.getText())) {
            erreurMsg += "Le Nom est invalide.\n";
            result = false;
        } else if (!utils.Validators.NomPrenomValidator(prenomTf.getText())) {
            erreurMsg += "Le Prennom est invalide.\n";
            result = false;
        } else if (!utils.Validators.DateValidator(datedenaissanceTf.getText())) {
            erreurMsg += "Le Format de la date est incorecte .\n";
            result = false;
        } else if (!utils.Validators.ConfirmerMotDePasseValidator(passwordTf.getText(), confirmPasswordTf.getText())) {
            erreurMsg += "la confirmation du mot de passe est inccorecte \n";
            result = false;
        }
        if (!result) {
            JOptionPane.showMessageDialog(null, erreurMsg);
        }

        return result;
    }

    private void RemplissageChamps() {

        try {
            authentification = AuthentificationDAO.getInstance().findById(Entity.Session.getInstance().getUser().getIdAuthentification());

            if ((authentification.getType() == 'c')) {
                conducteur = (Conducteurs) authentification.getCompte();
                nomTf.setText(conducteur.getNom());
                prenomTf.setText(conducteur.getPrenom());
                adresseTf.setText(conducteur.getAdresse());
                numtelTf.setText(conducteur.getNumeroTel());
                emailTf.setText(conducteur.getEmail());
                datedenaissanceTf.setText(conducteur.getDateNaissance().toString());
                if (conducteur.getSexe() == 'M') {
                    sexeTf.setSelectedIndex(0);

                } else {
                    sexeTf.setSelectedIndex(1);
                }
                
            //Get les valeurs a l'entité voiture 
            if (conducteur.getIdVoitures().getIdvoiture()!=0 || conducteur.getIdVoitures()!=null)
            {
                voiture= conducteur.getIdVoitures();
                AnneeTf.setText(String.valueOf(voiture.getAnnee()));
                MarqueTf.setText(voiture.getMarque());
                ModeleTf.setText(voiture.getModele());
                NbrPlaceTf.setText(String.valueOf(voiture.getNbrplaces()));
                
                if(voiture.isEstclimatiser())
                    ClimatiseurBox.setSelected(true);
                else
                     ClimatiseurBox.setSelected(false);

                 if(voiture.isEnfant())
                    EnfantBox.setSelected(true);
                else
                    EnfantBox.setSelected(false);

                  if(voiture.isBagage())
                    BagageBox.setSelected(true);
                else
                    BagageBox.setSelected(false);

                  if(voiture.isTabac())
                   TabacBox.setSelected(true);
                else
                    TabacBox.setSelected(false);
                 // fin 
        
            }
          }

        } catch (ProblemeTechniqueException ex) {
            System.out.println("Probléme de recuperation des données");

        }

    }

    private void setAllDesable() {
        nomTf.enable(false);
        prenomTf.enable(false);
        adresseTf.enable(false);
        numtelTf.enable(false);
        datedenaissanceTf.enable(false);
        sexeTf.enable(false);
        emailTf.enable(false);
        passwordTf.enable(false);
        confirmPasswordTf.enable(false);
         ModeleTf.enable(false);
        AnneeTf.enable(false);
        MarqueTf.enable(false);
        NbrPlaceTf.enable(false);
        ClimatiseurBox.setEnabled(false);
        EnfantBox.setEnabled(false);
        TabacBox.setEnabled(false);
        BagageBox.setEnabled(false);



    }

    private void setAllEnable() {
        nomTf.enable(true);
        prenomTf.enable(true);
        adresseTf.enable(true);
        numtelTf.enable(true);
        datedenaissanceTf.enable(true);
        sexeTf.enable(true);
        emailTf.enable(true);
        passwordTf.enable(true);
        confirmPasswordTf.enable(true);
        ModeleTf.enable(true);
        AnneeTf.enable(true);
        MarqueTf.enable(true);
        NbrPlaceTf.enable(true);
        ClimatiseurBox.setEnabled(true);
        EnfantBox.setEnabled(true);
        TabacBox.setEnabled(true);
        BagageBox.setEnabled(true);
    }
    private void nomTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTfActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setAllDesable();
        VoiturePanel.setVisible(false);
        AnnulerBtn.setVisible(false);
        EnregistrerBtn.setVisible(false);
        formaDate.setVisible(false);


        RemplissageChamps();


    }//GEN-LAST:event_formWindowOpened

    private void ModifierBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierBtnMouseClicked
        ModifierBtn.setVisible(false);
        AnnulerBtn.setVisible(true);
        EnregistrerBtn.setVisible(true);
        formaDate.setVisible(true);
        setAllEnable();

    }//GEN-LAST:event_ModifierBtnMouseClicked

    private void AnnulerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerBtnMouseClicked
        ModifierBtn.setVisible(true);
        AnnulerBtn.setVisible(false);
        EnregistrerBtn.setVisible(false);
        formaDate.setVisible(false);
        RemplissageChamps();
        setAllDesable();


    }//GEN-LAST:event_AnnulerBtnMouseClicked

    private void ModifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifierBtnActionPerformed

    private void EnregistrerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnregistrerBtnMouseClicked
        ModifierBtn.setVisible(true);
        AnnulerBtn.setVisible(true);
        EnregistrerBtn.setVisible(false);
        
        if (verifierChamps()) {
            if (!passwordTf.getText().equals("")) {
                authentification.setPassword(utils.Functions.ConvertToMd5 (passwordTf.getText()));
            }
            
            conducteur.setNom(nomTf.getText());
            conducteur.setPrenom(prenomTf.getText());
            conducteur.setAdresse(adresseTf.getText());
            conducteur.setNumeroTel(numtelTf.getText());
            conducteur.setEmail(emailTf.getText());
            java.text.SimpleDateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd");

            conducteur.setDateNaissance(new Date(new java.util.Date().getTime()));
            
            System.out.println(conducteur.getDateNaissance());
            
            if (sexeTf.getSelectedIndex()== 0)
            {
                conducteur.setSexe('M');
            }
            else 
                conducteur.setSexe('F');
            //Setter les valeurs a l'entité voiture 
            voiture.setAnnee(Integer.parseInt(AnneeTf.getText()));
            voiture.setMarque(MarqueTf.getText());
            voiture.setModele(ModeleTf.getText());
            voiture.setNbrplaces(Integer.parseInt(NbrPlaceTf.getText()));
            if(ClimatiseurBox.isSelected())
                voiture.setEstclimatiser(true);
            else
                voiture.setEstclimatiser(false);
            
             if(EnfantBox.isSelected())
                voiture.setEnfant(true);
            else
                voiture.setEnfant(false);
             
              if(BagageBox.isSelected())
                voiture.setBagage(true);
            else
                voiture.setBagage(false);
              
              if(TabacBox.isSelected())
                voiture.setTabac(true);
            else
                voiture.setTabac(false);
            // fin 
        }
        try {
                if (AuthentificationDAO.getInstance().update(authentification))
                {
                     if (conducteur.getIdVoitures().getIdvoiture()==0)
                     {
                        if (VoitureDAO.getInstance().create(voiture)) 
                        {
                           JOptionPane.showMessageDialog(null, "La modification de votre profile a été abouti");
                           formaDate.setVisible(false); 
                        }
                     }
                     else
                     {
                        if (VoitureDAO.getInstance().update(voiture)) 
                        {
                           JOptionPane.showMessageDialog(null, "La modification de votre profile a été abouti");
                           formaDate.setVisible(false); 
                        } 
                     }
                     
        
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "La modification n'a pas été abouti");
                }
            
        } catch (ProblemeTechniqueException ex) {
            System.out.println("Probléme de mise à jour ");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GestionProfil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GestionProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        AnnulerBtn.setVisible(false);
        setAllDesable();
        
    }//GEN-LAST:event_EnregistrerBtnMouseClicked

    private void AcceuilBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilBtnMouseClicked
       this.dispose();
    }//GEN-LAST:event_AcceuilBtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (VoiturePanel.isVisible())
        {
            VoiturePanel.setVisible(false);
        }
        else if (!VoiturePanel.isVisible())
        {
             VoiturePanel.setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProfil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceuilBtn;
    private javax.swing.JTextField AnneeTf;
    private javax.swing.JButton AnnulerBtn;
    private javax.swing.JCheckBox BagageBox;
    private javax.swing.JCheckBox ClimatiseurBox;
    private javax.swing.JCheckBox EnfantBox;
    private javax.swing.JButton EnregistrerBtn;
    private javax.swing.JTextField MarqueTf;
    private javax.swing.JTextField ModeleTf;
    private javax.swing.JButton ModifierBtn;
    private javax.swing.JLabel NbrPlaceTf;
    private javax.swing.JCheckBox TabacBox;
    private javax.swing.JPanel VoiturePanel;
    private javax.swing.JTextField adresseTf;
    private javax.swing.JTextField confirmPasswordTf;
    private javax.swing.JTextField datedenaissanceTf;
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel formaDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomTf;
    private javax.swing.JTextField numtelTf;
    private javax.swing.JTextField passwordTf;
    private javax.swing.JTextField prenomTf;
    private javax.swing.JComboBox sexeTf;
    // End of variables declaration//GEN-END:variables
}
