/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Conductuer;

import DAO.ConducteursDAO;
import Entity.Conducteurs;
import Entity.Session;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.ConducteurMetier;
import org.jfree.chart.ChartPanel;
import utils.Exceptions.ProblemeTechniqueException;

/**
 *
 * @author Amine
 */
public class Statistique extends javax.swing.JFrame {

    /**
     * Creates new form Statistique
     */
    ConducteurMetier conducteurMetier;
    public Statistique() {
        initComponents();
        conducteurMetier = new ConducteurMetier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filterStatCompte = new javax.swing.JPanel();
        filterYearLabel = new javax.swing.JLabel();
        filterYear = new javax.swing.JSpinner();
        genererStat = new javax.swing.JButton();
        filterMonthLabel = new javax.swing.JLabel();
        filterMonth = new javax.swing.JComboBox();
        affichageStatPanel = new javax.swing.JPanel();
        messageStatLabel = new javax.swing.JLabel();
        Accueil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Conducteur || statistiques");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Statistiques :");

        filterYearLabel.setText("Année :");

        genererStat.setText("Generer");
        genererStat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                genererStatMousePressed(evt);
            }
        });

        filterMonthLabel.setText("Mois:");

        filterMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toute l'année", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novombre", "Décembre" }));

        javax.swing.GroupLayout filterStatCompteLayout = new javax.swing.GroupLayout(filterStatCompte);
        filterStatCompte.setLayout(filterStatCompteLayout);
        filterStatCompteLayout.setHorizontalGroup(
            filterStatCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterStatCompteLayout.createSequentialGroup()
                .addComponent(genererStat)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(filterStatCompteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterStatCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filterYear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(filterStatCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filterStatCompteLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(filterMonthLabel))
                    .addGroup(filterStatCompteLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(filterMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        filterStatCompteLayout.setVerticalGroup(
            filterStatCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterStatCompteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterStatCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterYearLabel)
                    .addComponent(filterMonthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filterStatCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genererStat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        affichageStatPanel.setLayout(new java.awt.BorderLayout());

        Accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Accueil.png"))); // NOI18N
        Accueil.setText("Accueil");
        Accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccueilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(affichageStatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(messageStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filterStatCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(filterStatCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(messageStatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(affichageStatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generStat(){
        Conducteurs c = (Conducteurs) Session.getInstance().getUser().getCompte();
        int year = Integer.parseInt(filterYear.getValue().toString());
        try {
            affichageStatPanel.removeAll();
            
            if (filterMonth.getSelectedIndex() == 0)
            {
                affichageStatPanel.add(new ChartPanel(conducteurMetier.getbeneficeByYear(c.getIdConducteurs(), year)));
                messageStatLabel.setText("Bénéfice total: "+ ConducteursDAO.getInstance().getBeneficeByidConcducteur(c.getIdConducteurs(), 0) + " DT");
            }
            else
            {
                messageStatLabel.setText("Bénéfice : "+ ConducteursDAO.getInstance().getBeneficeByidConcducteurInMonth(c.getIdConducteurs(), year, filterMonth.getSelectedIndex()) + " DT");
                affichageStatPanel.add(new ChartPanel(conducteurMetier.getbeneficeByYearAndMonth(c.getIdConducteurs(), year ,filterMonth.getSelectedIndex())));
            }
            affichageStatPanel.validate();
        } catch (ProblemeTechniqueException ex) {
            JOptionPane.showMessageDialog(null, "il ya un probleme technique", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    filterYear.setValue(Calendar.getInstance().get(Calendar.YEAR)-1);
        
    generStat();
    }//GEN-LAST:event_formWindowOpened

    private void genererStatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genererStatMousePressed
        System.out.println("gener tenzel");
        generStat();
    }//GEN-LAST:event_genererStatMousePressed

    private void AccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilMouseClicked
        (new GUI.Conductuer.Accueil()).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_AccueilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accueil;
    private javax.swing.JPanel affichageStatPanel;
    private javax.swing.JComboBox filterMonth;
    private javax.swing.JLabel filterMonthLabel;
    private javax.swing.JPanel filterStatCompte;
    private javax.swing.JSpinner filterYear;
    private javax.swing.JLabel filterYearLabel;
    private javax.swing.JButton genererStat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel messageStatLabel;
    // End of variables declaration//GEN-END:variables
}
