/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.GestionProfil;

import Entity.Administrateur;
import Entity.Authentification;
import java.sql.Date;
import java.text.ParseException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.Exceptions.ProblemeTechniqueException;

/**
 *
 * @author Ahmed
 */
public class GestionProfil extends javax.swing.JFrame {

    private Authentification authentification = new Authentification();
    private Administrateur admin = new Administrateur();

    /**
     * Creates new form GestionProfil
     */
    public GestionProfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomTf = new javax.swing.JTextField();
        prenomTf = new javax.swing.JTextField();
        adresseTf = new javax.swing.JTextField();
        numtelTf = new javax.swing.JTextField();
        datedenaissanceTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JTextField();
        confirmPasswordTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EnregistrerBtn = new javax.swing.JButton();
        AcceuilBtn = new javax.swing.JButton();
        ModifierBtn = new javax.swing.JButton();
        AnnulerBtn = new javax.swing.JButton();
        sexeTf = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        jLabel3.setText("Adresse");

        jLabel4.setText("Numero de telephone");

        jLabel5.setText("Date de naissance");

        jLabel6.setText("Sexe");

        jLabel7.setText("E-mail");

        nomTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTfActionPerformed(evt);
            }
        });

        jLabel8.setText("Password");

        jLabel9.setText("Confirmer password");

        EnregistrerBtn.setText("Enregistrer");
        EnregistrerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnregistrerBtnMouseClicked(evt);
            }
        });

        AcceuilBtn.setText("Acceuil");

        ModifierBtn.setText("Modifier");
        ModifierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierBtnMouseClicked(evt);
            }
        });
        ModifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBtnActionPerformed(evt);
            }
        });

        AnnulerBtn.setText("Annuler");
        AnnulerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerBtnMouseClicked(evt);
            }
        });

        sexeTf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailTf)
                            .addComponent(datedenaissanceTf)
                            .addComponent(numtelTf)
                            .addComponent(adresseTf)
                            .addComponent(nomTf)
                            .addComponent(prenomTf)
                            .addComponent(passwordTf)
                            .addComponent(confirmPasswordTf)
                            .addComponent(sexeTf, 0, 87, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AcceuilBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModifierBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnregistrerBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnnulerBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prenomTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adresseTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(numtelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(datedenaissanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(sexeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnregistrerBtn)
                    .addComponent(AcceuilBtn)
                    .addComponent(ModifierBtn)
                    .addComponent(AnnulerBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean verifierChamps() {
        String erreurMsg = "";
        boolean result = true;

        if (nomTf.getText().length() < 3) {
            erreurMsg += "Le nom doit au moins avoir trois caracteres.\n";
            result = false;
        }

        if (prenomTf.getText().length() < 3) {
            erreurMsg += "Le prenom doit au moins avoir trois caracteres.\n";
            result = false;
        }

        if (!utils.Validators.NumeroTelValidator(numtelTf.getText())) {
            erreurMsg += "Le numéro de téléphone n'est pas valide.\n";
            result = false;
        } else if (!utils.Validators.TailleNumTelValidator(numtelTf.getText())) {
            erreurMsg += "Le numéro de téléphone est supérieur a 8 chiffre .\n";
            result = false;
        } else if (!utils.Validators.NomPrenomValidator(nomTf.getText())) {
            erreurMsg += "Le Nom est invalide.\n";
            result = false;
        } else if (!utils.Validators.NomPrenomValidator(prenomTf.getText())) {
            erreurMsg += "Le Prennom est invalide.\n";
            result = false;
        } else if (!utils.Validators.DateValidator(datedenaissanceTf.getText())) {
            erreurMsg += "Le Format de la date est incorecte .\n";
            result = false;
        } else if (!utils.Validators.ConfirmerMotDePasseValidator(passwordTf.getText(), confirmPasswordTf.getText())) {
            erreurMsg += "la confirmation du mot de passe est inccorecte \n";
            result = false;
        }
        if (!result) {
            JOptionPane.showMessageDialog(null, erreurMsg);
        }

        return result;
    }

    private void RemplissageChamps() {

        try {
            authentification = DAO.AuthentificationDAO.getInstance().findById(Entity.Session.getInstance().getUser().getIdAuthentification());

            if (authentification.getType() == 'a') {
                admin = (Administrateur) authentification.getCompte();
                nomTf.setText(admin.getNom());
                prenomTf.setText(admin.getPrenom());
                adresseTf.setText(admin.getAdresse());
                numtelTf.setText(admin.getNumeroTel());
                emailTf.setText(admin.getEmail());
                datedenaissanceTf.setText(admin.getDateNaissance().toString());
                if (admin.getSexe() == 'M') {
                    sexeTf.setSelectedIndex(0);

                } else {
                    sexeTf.setSelectedIndex(1);
                }


            }

        } catch (ProblemeTechniqueException ex) {
            System.out.println("Probléme de recuperation des données");

        }

    }

    private void setAllDesable() {
        nomTf.enable(false);
        prenomTf.enable(false);
        adresseTf.enable(false);
        numtelTf.enable(false);
        datedenaissanceTf.enable(false);
        sexeTf.enable(false);
        emailTf.enable(false);
        passwordTf.enable(false);
        confirmPasswordTf.enable(false);
        



    }

    private void setAllEnable() {
        nomTf.enable(true);
        prenomTf.enable(true);
        adresseTf.enable(true);
        numtelTf.enable(true);
        datedenaissanceTf.enable(true);
        sexeTf.enable(true);
        emailTf.enable(true);
        passwordTf.enable(true);
        confirmPasswordTf.enable(true);



    }
    private void nomTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTfActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setAllDesable();
        AnnulerBtn.setVisible(false);
        EnregistrerBtn.setVisible(false);


        RemplissageChamps();


    }//GEN-LAST:event_formWindowOpened

    private void ModifierBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierBtnMouseClicked
        ModifierBtn.setVisible(false);
        AnnulerBtn.setVisible(true);
        EnregistrerBtn.setVisible(true);

        setAllEnable();

    }//GEN-LAST:event_ModifierBtnMouseClicked

    private void AnnulerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerBtnMouseClicked
        ModifierBtn.setVisible(true);
        AnnulerBtn.setVisible(false);
        EnregistrerBtn.setVisible(false);
        RemplissageChamps();

        setAllDesable();


    }//GEN-LAST:event_AnnulerBtnMouseClicked

    private void ModifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifierBtnActionPerformed

    private void EnregistrerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnregistrerBtnMouseClicked
        ModifierBtn.setVisible(true);
        AnnulerBtn.setVisible(true);
        EnregistrerBtn.setVisible(false);
        if (verifierChamps()) {
            if (!passwordTf.getText().equals("")) {
                authentification.setPassword(utils.Functions.ConvertToMd5 (passwordTf.getText()));
            }
            
            admin.setNom(nomTf.getText());
            admin.setPrenom(prenomTf.getText());
            admin.setAdresse(adresseTf.getText());
            admin.setNumeroTel(numtelTf.getText());
            admin.setEmail(emailTf.getText());
            java.text.SimpleDateFormat df = new java.text.SimpleDateFormat("yyyy-mm-dd");
            try {
                admin.setDateNaissance(df.parse(datedenaissanceTf.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(GestionProfil.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(admin.getDateNaissance());
            
            if (sexeTf.getSelectedIndex()== 0)
            {
                admin.setSexe('M');
            }
            else 
                admin.setSexe('F');
        }
        try {
            DAO.AuthentificationDAO.getInstance().update(authentification);
        } catch (ProblemeTechniqueException ex) {
            System.out.println("Probléme de mise à jour ");
        }
        
    }//GEN-LAST:event_EnregistrerBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProfil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceuilBtn;
    private javax.swing.JButton AnnulerBtn;
    private javax.swing.JButton EnregistrerBtn;
    private javax.swing.JButton ModifierBtn;
    private javax.swing.JTextField adresseTf;
    private javax.swing.JTextField confirmPasswordTf;
    private javax.swing.JTextField datedenaissanceTf;
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomTf;
    private javax.swing.JTextField numtelTf;
    private javax.swing.JTextField passwordTf;
    private javax.swing.JTextField prenomTf;
    private javax.swing.JComboBox sexeTf;
    // End of variables declaration//GEN-END:variables
}
