/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.GererUtilisateur;

/**
 *
 * @author sabri
 */
public class GererUtilisateur extends javax.swing.JFrame {

    /**
     * Creates new form GererUtilisateur
     */
    public GererUtilisateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConducteurBtn = new javax.swing.JButton();
        PassagerBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        ConducteurBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Conductuer.jpg"))); // NOI18N
        ConducteurBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConducteurBtnMouseClicked(evt);
            }
        });
        getContentPane().add(ConducteurBtn);
        ConducteurBtn.setBounds(120, 180, 140, 130);

        PassagerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Passager.png"))); // NOI18N
        PassagerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassagerBtnMouseClicked(evt);
            }
        });
        getContentPane().add(PassagerBtn);
        PassagerBtn.setBounds(490, 180, 140, 130);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConducteurBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConducteurBtnMouseClicked
          GUI.GererUtilisateur.GererConducteur acc = new GUI.GererUtilisateur.GererConducteur();
            acc.setVisible(true);
    }//GEN-LAST:event_ConducteurBtnMouseClicked

    private void PassagerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassagerBtnMouseClicked
        GUI.GererUtilisateur.GererPassager acc = new GUI.GererUtilisateur.GererPassager();
         acc.setVisible(true);
    }//GEN-LAST:event_PassagerBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererUtilisateur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConducteurBtn;
    private javax.swing.JButton PassagerBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
