/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.GestionRapports;

import Entity.*;
import metier.*;
import utils.components.jtable.*;

/**
 *
 * @author user
 */
public class GestionRapports extends javax.swing.JFrame {

    /**
     * Creates new form GestionRapports
     */
    Rapport rapport;
    Banissement banissement;
    Itineraire itineraire;
    Conducteurs conducteur ; 
    Passagers passager ;
    String userbanned ;
    
    metier.RapportMetier rapprotmetier;
    metier.BanissementMetier banissementmetier;
    metier.ItineraireMetier itinerairemetier;
    
    
    public GestionRapports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        datagrid = new javax.swing.JTable();
        Bannirbtn = new javax.swing.JButton();
        Avertirbtn = new javax.swing.JButton();
        user1 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        NbrBannit = new javax.swing.JLabel();
        NbrRapporter = new javax.swing.JLabel();
        Acceuilbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoItinerraire = new javax.swing.JTextArea();
        user = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        datagrid.setModel(new utils.components.jtable.tableModelGererRapport());
        datagrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datagridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datagrid);

        Bannirbtn.setText("Bannir");
        Bannirbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BannirbtnMouseClicked(evt);
            }
        });
        Bannirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BannirbtnActionPerformed(evt);
            }
        });

        Avertirbtn.setText("Avertir");
        Avertirbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvertirbtnMouseClicked(evt);
            }
        });

        Acceuilbtn.setText("Acceuil");
        Acceuilbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceuilbtnActionPerformed(evt);
            }
        });

        infoItinerraire.setColumns(20);
        infoItinerraire.setRows(5);
        jScrollPane2.setViewportView(infoItinerraire);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(488, 488, 488)
                                .addComponent(NbrRapporter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NbrBannit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 215, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                            .addComponent(user))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bannirbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Avertirbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Acceuilbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bannirbtn)
                                .addGap(41, 41, 41)
                                .addComponent(Avertirbtn)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NbrBannit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NbrRapporter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(Acceuilbtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void remplirinformations(int ligne)
    {
         Rapport rapport= ((tableModelGererRapport)datagrid.getModel()).getRowEntity(ligne);
         Itineraire itineraire=rapport.getIditineraire();
         passager = rapport.getIdPassager();
         conducteur = itineraire.getIdConducteur();
         if (rapport.isRapporterConducteur())
         { 
             user.setText("Le Passager "+passager.getNom()+" "+passager.getPrenom()+" à rapporter le conducteur "+conducteur.getNom()+" "+conducteur.getPrenom());
             userbanned="c";
         }
         else
         {
             user.setText("Le conducteur '"+conducteur.getNom()+" "+conducteur.getPrenom()+"' à rapporter  Le Passager '"+passager.getNom()+" "+passager.getPrenom()+"'");
              userbanned="p";
         }
         String info = "L'itinéraire meuner par le conducteur"+conducteur.getNom()+" "+conducteur.getPrenom()+" à la date "+itineraire.getDateitineraire().toGMTString()
                        +"\n publier le "+itineraire.getDatepublication().toGMTString()+" Pour une distance de "+itineraire.getDistanceitineraire()+" .";
         infoItinerraire.setText(info);
         
    }
    private void AcceuilbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceuilbtnActionPerformed
        // TODO add your handling code here:
       (new GUI.Administrateur.Accueil()).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_AcceuilbtnActionPerformed

    private void BannirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BannirbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BannirbtnActionPerformed

    private void datagridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datagridMouseClicked
        
        remplirinformations(datagrid.getSelectedRow());
        Bannirbtn.setVisible(true);
        Avertirbtn.setVisible(true);
        infoItinerraire.setVisible(true);
    }//GEN-LAST:event_datagridMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       infoItinerraire.disable();
       user.disable();
       Bannirbtn.setVisible(false);
       Avertirbtn.setVisible(false);
       infoItinerraire.setVisible(false);
      
    }//GEN-LAST:event_formWindowOpened

    private void BannirbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BannirbtnMouseClicked
       GUI.Banissement.Banissement acc = new GUI.Banissement.Banissement(conducteur,passager,userbanned);
            acc.setVisible(true);
        
        
    }//GEN-LAST:event_BannirbtnMouseClicked

    private void AvertirbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvertirbtnMouseClicked
        
       GUI.Avertir.Avertir acc = new GUI.Avertir.Avertir (conducteur,passager,userbanned);
            acc.setVisible(true);
    }//GEN-LAST:event_AvertirbtnMouseClicked

 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionRapports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionRapports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionRapports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionRapports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionRapports().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acceuilbtn;
    private javax.swing.JButton Avertirbtn;
    private javax.swing.JButton Bannirbtn;
    private javax.swing.JLabel NbrBannit;
    private javax.swing.JLabel NbrRapporter;
    private javax.swing.JTable datagrid;
    private javax.swing.JTextArea infoItinerraire;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField user;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    // End of variables declaration//GEN-END:variables
}
