/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MotDePasseOublier;

import javax.swing.JOptionPane;
import DAO.*;
import Entity.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.Exceptions.ProblemeTechniqueException;
import utils.Mail;
/**
 *
 * @author Axel
 */
public class MotDePasseOublier extends javax.swing.JFrame {
  
     private Mail mail ;
     private String Password ; 
     private String PasswordMD5;
     private String logins ;
    /**
     * Creates new form MotDePasseOublier
     */
    public MotDePasseOublier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Verifier = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();
        Email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JCheckBox();
        MDP = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Votre Mail  : ");

        Verifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Envoyer.png"))); // NOI18N
        Verifier.setText("Envoyer");
        Verifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerifierMouseClicked(evt);
            }
        });

        Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/quitter.png"))); // NOI18N
        Quitter.setText("Quitter");
        Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterMouseClicked(evt);
            }
        });

        jLabel2.setText("Récupérer :");

        login.setText("Login ");

        MDP.setText("Mot de passe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(Verifier, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MDP)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(login)
                    .addComponent(MDP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Verifier)
                    .addComponent(Quitter)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterMouseClicked
        this.dispose();
    }//GEN-LAST:event_QuitterMouseClicked

    private void VerifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifierMouseClicked
        Password= "";
        PasswordMD5="";
        logins ="";
        
        if(!utils.Validators.EmailValidator(Email.getText()))
        {
             JOptionPane.showMessageDialog(null, "Vous avez mal tapé votre mail");
        }
        else
        {
            Administrateur a = new Administrateur();
            Conducteurs c = new Conducteurs();
            Passagers p = new Passagers();
            Authentification  auth = new Authentification();
            try {
                    a = AdministrateurDAO.getInstance().findByEmail(Email.getText());
                    c = ConducteursDAO.getInstance().getByEmail(Email.getText());
                    p = PassagersDAO.getInstance().getPassagerByEmail(Email.getText());
                    
            } catch (ProblemeTechniqueException ex) {
                Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
            }
                if (a!=null)
                {
                   if(MDP.isSelected() && !login.isSelected())
                   {
                            JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                            String Mymail = Email.getText();
                            Password = utils.Functions.RandomPassword();
                            PasswordMD5 = utils.Functions.ConvertToMd5(Password);
                            String message = "Bonjour administrateur "+a.getNom()+" "+a.getPrenom()+" vous avez oublié votre mot de passe un mot de passe"
                                           + " aléatoire a étè génerer pour vous , veuillez le changer dés votre connexion \n"
                                           + "Votre noveau mot de passe est : "+Password ;
                         try {
                                auth = AuthentificationDAO.getInstance().getByIdCompteAndType(a.getIdAdministrateurs(),"a");
                                auth.setPassword(PasswordMD5);
                                auth.setCompte((Administrateur)a);
                             AuthentificationDAO.getInstance().update(auth);
                             mail = new Mail(Mymail);
                             mail.SetObjectMail("Récuperation identifiant");
                             mail.SetContenuMail(message);
                             mail.envoyerMail();
                             JOptionPane.showMessageDialog(null, "Un mail qui contient votre nouveau mot de passe vous a étè transmis.");
                             this.dispose();
                        } catch (Exception ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        }
                   else if (!MDP.isSelected() && login.isSelected())
                   {
                         
                         try {
                                auth = AuthentificationDAO.getInstance().getByIdCompteAndType(a.getIdAdministrateurs(),"a");
                                JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                                String Mymail = Email.getText();
                                String message = "Bonjour administrateur "+a.getNom()+" "+a.getPrenom()+" vous avez oublié votre login \n"  
                                               + "Votre Login est : "+auth.getLogin() ;
                             
                             try {
                                    
                                     mail = new Mail(Mymail);
                                     mail.SetObjectMail("Récuperation identifiant");
                                     mail.SetContenuMail(message);
                                     mail.envoyerMail();
                                 JOptionPane.showMessageDialog(null, "Un mail qui contient votre Login vous a étè transmis.");
                                 this.dispose();
                            } catch (Exception ex) {
                                Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                            }
                       } catch (ProblemeTechniqueException ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }
                   }
                   else if (MDP.isSelected() && login.isSelected())
                   {
                       try {
                           auth = AuthentificationDAO.getInstance().getByIdCompteAndType(a.getIdAdministrateurs(),"a");
                       } catch (ProblemeTechniqueException ex) {
                           Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                       }
                            JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                            String Mymail = Email.getText();
                            Password = utils.Functions.RandomPassword();
                            PasswordMD5 = utils.Functions.ConvertToMd5(Password);
                            String message = "Bonjour administrateur "+a.getNom()+" "+a.getPrenom()+" vous avez oublié votre login et mot de passe. \n Un mot de passe"
                                           + " aléatoire a étè génerer pour vous , veuillez le changer dés votre connexion \n"
                                           + "Votre Login : "+auth.getLogin()+"\n Votre noveau mot de passe est : "+Password ;
                         try {
                                
                                auth.setPassword(PasswordMD5);
                                auth.setCompte((Administrateur)a);
                             AuthentificationDAO.getInstance().update(auth);
                             mail = new Mail(Mymail);
                             mail.SetObjectMail("Récuperation identifiant");
                             mail.SetContenuMail(message);
                             mail.envoyerMail();
                             JOptionPane.showMessageDialog(null, "Un mail qui contient votre login et votre nouveau mot de passe vous a étè transmis.");
                             this.dispose();
                        } catch (Exception ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }

                   }
                   else if (!MDP.isSelected() && !login.isSelected())
                   {
                       JOptionPane.showMessageDialog(null, "Veuillez cocher l'une des options.");
                   }
                }
                else if (c!=null)
                {
                    if(MDP.isSelected() && !login.isSelected())
                   {
                            JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                            String Mymail = Email.getText();
                            Password = utils.Functions.RandomPassword();
                            PasswordMD5 = utils.Functions.ConvertToMd5(Password);
                            String message = "Bonjour conducteur "+c.getNom()+" "+c.getPrenom()+" vous avez oublié votre mot de passe un mot de passe"
                                           + " aléatoire a étè génerer pour vous , veuillez le changer dés votre connexion \n"
                                           + "Votre noveau mot de passe est : "+Password ;
                         try {
                                auth = AuthentificationDAO.getInstance().getByIdCompteAndType(c.getIdConducteurs(),"c");
                                auth.setPassword(PasswordMD5);
                                auth.setCompte((Conducteurs)c);
                             AuthentificationDAO.getInstance().update(auth);
                             mail = new Mail(Mymail);
                             mail.SetObjectMail("Récuperation identifiant");
                             mail.SetContenuMail(message);
                             mail.envoyerMail();
                             JOptionPane.showMessageDialog(null, "Un mail qui contient votre nouveau mot de passe vous a étè transmis.");
                             this.dispose();
                        } catch (Exception ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        }
                   else if (!MDP.isSelected() && login.isSelected())
                   {
                         
                         try {
                                auth = AuthentificationDAO.getInstance().getByIdCompteAndType(c.getIdConducteurs(),"c");
                                JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                                String Mymail = Email.getText();
                                String message = "Bonjour conducteur "+c.getNom()+" "+c.getPrenom()+" vous avez oublié votre login \n"  
                                               + "Votre Login est : "+auth.getLogin() ;
                             
                             try {
                                    
                                     mail = new Mail(Mymail);
                                     mail.SetObjectMail("Récuperation identifiant");
                                     mail.SetContenuMail(message);
                                     mail.envoyerMail();
                                 JOptionPane.showMessageDialog(null, "Un mail qui contient votre Login vous a étè transmis.");
                                 this.dispose();
                            } catch (Exception ex) {
                                Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                            }
                       } catch (ProblemeTechniqueException ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }
                   }
                   else if (MDP.isSelected() && login.isSelected())
                   {
                       try {
                           auth = AuthentificationDAO.getInstance().getByIdCompteAndType(c.getIdConducteurs(),"c");
                       } catch (ProblemeTechniqueException ex) {
                           Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                       }
                            JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                            String Mymail = Email.getText();
                            Password = utils.Functions.RandomPassword();
                            PasswordMD5 = utils.Functions.ConvertToMd5(Password);
                            String message = "Bonjour conducteur "+c.getNom()+" "+c.getPrenom()+" vous avez oublié votre login et mot de passe. \n Un mot de passe"
                                           + " aléatoire a étè génerer pour vous , veuillez le changer dés votre connexion \n"
                                           + "Votre Login : "+auth.getLogin()+"\n Votre noveau mot de passe est : "+Password ;
                         try {
                                
                                auth.setPassword(PasswordMD5);
                                auth.setCompte((Conducteurs)c);
                             AuthentificationDAO.getInstance().update(auth);
                             mail = new Mail(Mymail);
                             mail.SetObjectMail("Récuperation identifiant");
                             mail.SetContenuMail(message);
                             mail.envoyerMail();
                             JOptionPane.showMessageDialog(null, "Un mail qui contient votre login et votre nouveau mot de passe vous a étè transmis.");
                             this.dispose();
                        } catch (Exception ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }

                   }
                   else if (!MDP.isSelected() && !login.isSelected())
                   {
                       JOptionPane.showMessageDialog(null, "Veuillez cocher l'une des options.");
                   }
                }
                else if (p.getIdPassagers()!=0)
                {
                       if(MDP.isSelected() && !login.isSelected())
                   {
                            JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                            String Mymail = Email.getText();
                            Password = utils.Functions.RandomPassword();
                            PasswordMD5 = utils.Functions.ConvertToMd5(Password);
                            String message = "Bonjour passager "+p.getNom()+" "+p.getPrenom()+" vous avez oublié votre mot de passe un mot de passe"
                                           + " aléatoire a étè génerer pour vous , veuillez le changer dés votre connexion \n"
                                           + "Votre noveau mot de passe est : "+Password ;
                         try {
                                auth = AuthentificationDAO.getInstance().getByIdCompteAndType(p.getIdPassagers(),"p");
                                auth.setPassword(PasswordMD5);
                                auth.setCompte((Passagers)p);
                             AuthentificationDAO.getInstance().update(auth);
                             mail = new Mail(Mymail);
                             mail.SetObjectMail("Récuperation identifiant");
                             mail.SetContenuMail(message);
                             mail.envoyerMail();
                             JOptionPane.showMessageDialog(null, "Un mail qui contient votre nouveau mot de passe vous a étè transmis.");
                             this.dispose();
                        } catch (Exception ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        }
                   else if (!MDP.isSelected() && login.isSelected())
                   {
                         
                         try {
                                auth = AuthentificationDAO.getInstance().getByIdCompteAndType(p.getIdPassagers(),"p");
                                JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                                String Mymail = Email.getText();
                                String message = "Bonjour passager "+p.getNom()+" "+p.getPrenom()+" vous avez oublié votre login \n"  
                                               + "Votre Login est : "+auth.getLogin() ;
                             
                             try {
                                    
                                     mail = new Mail(Mymail);
                                     mail.SetObjectMail("Récuperation identifiant");
                                     mail.SetContenuMail(message);
                                     mail.envoyerMail();
                                 JOptionPane.showMessageDialog(null, "Un mail qui contient votre Login vous a étè transmis.");
                                 this.dispose();
                            } catch (Exception ex) {
                                Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                            }
                       } catch (ProblemeTechniqueException ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }
                   }
                   else if (MDP.isSelected() && login.isSelected())
                   {
                       try {
                           auth = AuthentificationDAO.getInstance().getByIdCompteAndType(p.getIdPassagers(),"p");
                       } catch (ProblemeTechniqueException ex) {
                           Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                       }
                            JOptionPane.showMessageDialog(null, "Votre Adresse Mail est verifier"); 
                            String Mymail = Email.getText();
                            Password = utils.Functions.RandomPassword();
                            PasswordMD5 = utils.Functions.ConvertToMd5(Password);
                            String message = "Bonjour passager "+p.getNom()+" "+p.getPrenom()+" vous avez oublié votre login et mot de passe. \n Un mot de passe"
                                           + " aléatoire a étè génerer pour vous , veuillez le changer dés votre connexion \n"
                                           + "Votre Login : "+auth.getLogin()+"\n Votre noveau mot de passe est : "+Password ;
                         try {
                                
                                auth.setPassword(PasswordMD5);
                                auth.setCompte((Passagers)p);
                             AuthentificationDAO.getInstance().update(auth);
                             mail = new Mail(Mymail);
                             mail.SetObjectMail("Récuperation identifiant");
                             mail.SetContenuMail(message);
                             mail.envoyerMail();
                             JOptionPane.showMessageDialog(null, "Un mail qui contient votre login et votre nouveau mot de passe vous a étè transmis.");
                             this.dispose();
                        } catch (Exception ex) {
                            Logger.getLogger(MotDePasseOublier.class.getName()).log(Level.SEVERE, null, ex);
                        }

                   }
                   else if (!MDP.isSelected() && !login.isSelected())
                   {
                       JOptionPane.showMessageDialog(null, "Veuillez cocher l'une des options.");
                   }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Votre Adresse Mail  n'existe pas , retapez votre adresse "); 
                }
        }
    }//GEN-LAST:event_VerifierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotDePasseOublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotDePasseOublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotDePasseOublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotDePasseOublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotDePasseOublier().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JCheckBox MDP;
    private javax.swing.JButton Quitter;
    private javax.swing.JButton Verifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox login;
    // End of variables declaration//GEN-END:variables
}
